spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

server:
  port: 8765

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}